### ISSUE TITLE
Icon character artifact

### ISSUE THREAD

**Issue by kr4k3n1s** [rickytan/RTViewAttachment#5]
I remade your solution to swift 5, but i can’t figure out how to hide icon “image” produced by placeholder character “\uFFFC” (i guess it´s that). Providing screenshot with partly transparent view.
![89F1A682-C19E-405A-A31A-F5972354DD7B](https://user-images.githubusercontent.com/72310426/131586867-634b33f9-3103-4570-97ea-dbbb8823e5b2.png)

**Comment by rickytan** [comment]
Is it works fine with OC ?

**Comment by jayying007** [comment]
you can override the method -[NSTextAttachmentContainer imageForBounds:textContainer:characterIndex:], and return nil.  which is in NSTextAttachment
